#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/install-tools
- include_tasks: packages.yml
- include_tasks: docker.yml
- include_tasks: kerbrute.yml
- include_tasks: github-repos.yml
- include_tasks: python-tools.yml
- include_tasks: gem-tools.yml
- include_tasks: oracle-odat.yml
